### PR TITLE
A feature added, and gitignore file updated

### PR DESCRIPTION
**Pull request by V01dZer0**
1. Added shouldQuoteEscapeSequence for CPQuotedRecogniser.

This property is very useful when parse multiline string in source code.
e.g. : a C string :

```
"Quick brown\
fox jumps over a lazy dog"
```

should be parsed into **Quick brown fox jumps over a lazy dog**,
not **Quick brown\ fox jumps over a lazy dog**.
And this work will be done only to set shouldQuoteEscapeSequence to YES.
1. Removed shared project config files, and updated gitignore file.

### CODE REVIEW

**Comment by beelsebob** [comment]
As I commented in the other patch - I'm not sure this makes sense.  Isn't this just an escapeRecogniser?

**Comment by OpenFibers** [comment]
@beelsebob I didn't find **escapeRecogniser** in CoreParse project, did you mean **escapeReplacer** ?

**Comment by siuying** [comment]
@OpenFibers its ``CPQuotedRecogniser`` https://github.com/beelsebob/CoreParse/blob/master/CoreParse/Tokenisation/Token%20Recognisers/CPQuotedRecogniser.h

**Comment by OpenFibers** [comment]
@beelsebob I see the escapeReplace covers the work shouldQuoteEscapeSequence can do, so forget shouldQuoteEscapeSequence, it's a bad idea.  
But you may want to merge commits of .gitignore and remove local config files.

**Pull request closed without merging**
